increase logger test coverage to 100%
oneapi-src/unified-memory-framework pull request #1002
Opened 2024-12-17 14:58 UTC by lplewa

### Description

### Checklist

- [ ] Code compiles without errors locally
- [ ] All tests pass locally
- [ ] CI workflows execute properly

- [ ] CI workflows, not executed per PR (e.g. Nightly), execute properly 
- [ ] New tests added, especially if they will fail without my changes
- [ ] Added/extended example(s) to cover this functionality
- [ ] Extended the README/documentation
- [ ] All newly added source files have a license
- [ ] All newly added source files are referenced in CMake files
- [ ] Logger (with debug/info/... messages) is used

2024-12-18 07:41 UTC, ldorau requested changes
CI builds fail

2024-12-18 07:41 UTC, ldorau commented on test/utils/utils_log.cpp
> +// This trick to not work on windows
maybe `does not` ?

2024-12-18 07:41 UTC, ldorau commented on test/utils/utils_log.cpp
> +// this test do not work on windows as we cannot mock abort on windows
does not

2025-01-16 10:51 UTC, ldorau commented
@lplewa ping

2025-01-17 14:26 UTC, KFilipek commented on test/utils/utils_log.cpp
> +// this test doesn't work on windows as we cannot mock abort on windows
`on windows` twice

2025-02-12 15:09 UTC, closed without merging