Add sles15 to multi numa ci
oneapi-src/unified-memory-framework pull request #1007
Opened 2024-12-18 13:06 UTC by intel12232289

Add sles15 to multi numa ci

2024-12-19 14:05 UTC, lukaszstolarczuk commented
using static hwloc linking (changes: https://github.com/intel12232289/unified-memory-framework/blob/refs/heads/Add-SLES15-to-multi-NUMA-C/.github/workflows/reusable_multi_numa.yml#L49 )

we got issues in testing, is this expected?
Log: https://github.com/intel12232289/unified-memory-framework/actions/runs/12411309212/job/34656468532

@ldorau, for the help? 😉

2024-12-20 07:19 UTC, ldorau commented
> using static hwloc linking (changes: https://github.com/intel12232289/unified-memory-framework/blob/refs/heads/Add-SLES15-to-multi-NUMA-C/.github/workflows/reusable_multi_numa.yml#L49 )
> 
> we got issues in testing, is this expected?
>

I think it is not, since it works correctly on Ubuntu 22.04;
https://github.com/oneapi-src/unified-memory-framework/actions/runs/12427135597/job/34696473613

2024-12-20 09:23 UTC, lukaszstolarczuk requested changes
ok, @intel12232289 it looks like there's some issue we may not understand.

Please make it as it was before - run only selected tests (similarly to RHEL), and please make the PR ready for review & merge

2024-12-20 09:23 UTC, lukaszstolarczuk commented on .github/workflows/reusable_multi_numa.yml
> +    # if: github.repository == 'oneapi-src/unified-memory-framework'
pls uncomment this

2024-12-20 09:23 UTC, lukaszstolarczuk commented on .github/workflows/reusable_multi_numa.yml
> +        os: [ubuntu-22.04, rhel-9.1, sles15]
pls re-name to `sles-15`

2024-12-20 09:23 UTC, lukaszstolarczuk commented on .github/workflows/reusable_multi_numa.yml
> +          -DUMF_LINK_HWLOC_STATICALLY=${{ matrix.os == 'sles15' && 'ON' || 'OFF' }}
you can remove this line now

2025-01-14 11:01 UTC, lukaszstolarczuk requested changes
Since we're ready with the machine, please cleanup the PR (see my issues) and we can un-draft it.

2025-01-14 11:01 UTC, lukaszstolarczuk commented on .github/workflows/reusable_multi_numa.yml
pls squash all your commits into a single one, with a proper description what this commit does

2025-01-14 13:06 UTC, intel12232289 commented
I will close this one. Too much conflicts during squashing 
https://github.com/oneapi-src/unified-memory-framework/pull/1037

2025-01-14 13:06 UTC, closed without merging