Set symbol versions 0.10 in def/map files
oneapi-src/unified-memory-framework pull request #1013
Opened 2024-12-23 15:24 UTC by lukaszstolarczuk

and unify names used in these files - "LIBUMF" and "LIBUMF_PROXY"

2024-12-30 11:15 UTC, KFilipek requested changes

2024-12-30 11:18 UTC, KFilipek commented
If you want to change the `umf` to `libumf` here is the patch that fixes above errors:
[umf_for_libumf.patch](https://github.com/user-attachments/files/18274249/umf_for_libumf.patch)

2024-12-30 11:26 UTC, bratpiorka commented
@lukaszstolarczuk If we can't keep the current lib name (just umf.dll) with this change, I would opt for leaving UMF_* in map/def as it is, rather than changing it to LIBUMF_* even if we would have UMF_1.0 twice in our history

2025-01-03 10:54 UTC, bratpiorka commented on src/proxy_lib/proxy_lib.map
> +UMF_PROXY_0.10 {
IMO to override glibc malloc/free they should be put in unnamed memspace

2025-01-03 11:03 UTC, bratpiorka commented on src/proxy_lib/proxy_lib.map
> +UMF_PROXY_0.10 {
+ add comment about this

2025-01-03 11:59 UTC, lukaszstolarczuk commented on RELEASE_STEPS.md
>    - These files are defined for all public libraries (`libumf` and `proxy_lib`, at the moment)
Done.

2025-01-03 12:00 UTC, lukaszstolarczuk commented on src/libumf.def
> +LIBRARY LIBUMF
Done.

2025-01-03 14:50 UTC, bratpiorka approved these changes

2025-01-03 16:14 UTC, KFilipek approved these changes

2025-01-03 16:14 UTC, merged