Unify global umf_ba_pool_t initialization
oneapi-src/unified-memory-framework pull request #229
Opened 2024-02-12 17:56 UTC by igchor

Initializing the global pool in libumf and in each pool separately led to problems with double initialization when multiple pools were used in a single application (and static libumf).

To avoid this problem, use util_init_once inside umf_ba_get_pool instead of having explicit constructor/destructor.

This fixes an issue exposed by:  0c55d8f55d583e87af4f08157c0ad1c828a02ac6

2024-02-12 17:57 UTC, igchor commented
This should have been tested by https://github.com/oneapi-src/unified-memory-framework/pull/223 but scalable pool was missing from the test. It's fixed here: https://github.com/oneapi-src/unified-memory-framework/pull/228

2024-02-12 20:09 UTC, ldorau approved these changes

2024-02-13 10:01 UTC, ldorau requested changes
There is an issue here. I am describing it just now ...

2024-02-13 11:12 UTC, ldorau approved these changes
However I think it should be merged as is, because it fixes the failure of #227 and refined later.

2024-02-13 11:19 UTC, bratpiorka approved these changes

2024-02-13 11:19 UTC, merged