Remove DisjointPoolConfig and use umf_helpers to expose DisjointPool ops
oneapi-src/unified-memory-framework pull request #30
Opened 2023-11-08 22:15 UTC by igchor

2023-11-10 10:54 UTC, ldorau requested changes
It does not build on Windows;
```
[  2%] Building CXX object src/CMakeFiles/unified_memory_framework.dir/pool/disjoint/pool_disjoint_impl.cpp.obj
pool_disjoint_impl.cpp
C:\Users\ldorau\work\unified-memory-framework\src\pool\disjoint\pool_disjoint_impl.cpp(296): error C2672: 'std::max': no matching overloaded function found
C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.35.32215\include\utility(51): note: could be '_Ty std::max(std::initializer_list<_Elem>)'
C:\Users\ldorau\work\unified-memory-framework\src\pool\disjoint\pool_disjoint_impl.cpp(296): note: '_Ty std::max(std::initializer_list<_Elem>)': expects 1 arguments - 2 provided
C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.35.32215\include\utility(48): note: or       '_Ty std::max(std::initializer_list<_Elem>,_Pr)'
C:\Users\ldorau\work\unified-memory-framework\src\pool\disjoint\pool_disjoint_impl.cpp(296): note: '_Ty std::max(std::initializer_list<_Elem>,_Pr)': could not deduce template argument for 'std::initializer_list<_Elem>' from 'size_t'
C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.35.32215\include\utility(41): note: or       'const _Ty &std::max(const _Ty &,const _Ty &) noexcept(<expr>)'
C:\Users\ldorau\work\unified-memory-framework\src\pool\disjoint\pool_disjoint_impl.cpp(296): note: 'const _Ty &std::max(const _Ty &,const _Ty &) noexcept(<expr>)': template parameter '_Ty' is ambiguous
C:\Users\ldorau\work\unified-memory-framework\src\pool\disjoint\pool_disjoint_impl.cpp(296): note: could be 'unsigned long'
C:\Users\ldorau\work\unified-memory-framework\src\pool\disjoint\pool_disjoint_impl.cpp(296): note: or       'size_t'
C:\Users\ldorau\work\unified-memory-framework\src\pool\disjoint\pool_disjoint_impl.cpp(296): note: 'const _Ty &std::max(const _Ty &,const _Ty &) noexcept(<expr>)': could not deduce template argument for 'const _Ty &' from 'unsigned long'
C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.35.32215\include\utility(31): note: or       'const _Ty &std::max(const _Ty &,const _Ty &,_Pr) noexcept(<expr>)'
C:\Users\ldorau\work\unified-memory-framework\src\pool\disjoint\pool_disjoint_impl.cpp(296): note: 'const _Ty &std::max(const _Ty &,const _Ty &,_Pr) noexcept(<expr>)': expects 3 arguments - 2 provided
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\unified_memory_framework.dir\pool\disjoint\pool_disjoint_impl.cpp.obj.d --working-dir=C:\Users\ldorau\work\unified-memory-framework\build\src --filter-prefix="Note: including file: " -- C:\PROGRA~1\MIB055~1\2022\PROFES~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\x64\cl.exe @C:\Users\ldorau\AppData\Local\Temp\nm241F.tmp' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.35.32215\bin\HostX64\x64\nmake.exe" -s -f src\CMakeFiles\unified_memory_framework.dir\build.make /nologo -SL                 src\CMakeFiles\unified_memory_framework.dir\build' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.35.32215\bin\HostX64\x64\nmake.exe" -s -f CMakeFiles\Makefile2 /nologo -S                  all' : return code '0x2'
Stop.
```

2023-11-17 09:41 UTC, bratpiorka commented
@igchor I thought we could keep C++ implementation in pool_disjoint_impl.* files and have a thin C-only wrapper for it in poll_disjoing.c/h. What do you think? Now there is a mix of C and C++ code in UMF and I think we should be more consistent here.

2023-11-17 17:11 UTC, igchor commented
It's still separated - the C++ implementation is in pool_disjoint_impl.* and the C wrapper is in pool_disjoint.c The only difference is that the wrapper now uses generic helpers, so that we can avoid the boilerplate and we don't have a separate C++-specific config type.

However, I'm not actually sure if there's any benefit in keeping those extra files. The pool_disjoint_impl.hpp won't be used anywhere other than by pool_disjoint.c anyway (we expect everyone to interact with disjoint pool through our C API, or C++ bindings on top of them) so I would actually suggest removing pool_disjoint_impl.hpp and pool_disjoint.c (and keeping only pool_disjoint.h and pool_disjoint_impl.cpp)

2023-11-20 11:23 UTC, pbalcer approved these changes

2023-11-20 15:52 UTC, ldorau approved these changes

2023-11-20 17:11 UTC, merged