Enable building L0 provider on Windows
oneapi-src/unified-memory-framework pull request #326
Opened 2024-03-12 14:53 UTC by bratpiorka

### Description

Enable building L0 provider on Windows. GPU testing will still not be enabled as we cannot yet test it in CI.

### Checklist

- [ ] Code compiles without errors locally
- [ ] All tests pass locally
- [ ] CI workflows execute properly

- [ ] New tests added, especially if they will fail without my changes
- [ ] Added/extended example(s) to cover this functionality
- [ ] Extended the README/documentation
- [ ] All newly added source files have a license
- [ ] All newly added source files are referenced in CMake files

2024-03-13 11:04 UTC, PatKamin approved these changes

2024-03-14 08:58 UTC, lukaszstolarczuk approved these changes
Can you please rebase, so we re-run the sanitizers tests?

2024-03-14 09:44 UTC, lukaszstolarczuk requested changes

2024-03-14 09:44 UTC, lukaszstolarczuk commented on .github/workflows/gpu.yml
> +          - os: 'windows-latest'
heh, this `os` param is not used actually 😄

2024-03-14 11:03 UTC, lukaszstolarczuk approved these changes

2024-03-14 11:04 UTC, merged