Enable logger in UMF tests
oneapi-src/unified-memory-framework pull request #470
Opened 2024-05-07 11:20 UTC by kswiecicki

It's easier to spot the cause of errors in tests with log messages.
### Description

### Checklist

- [ ] Code compiles without errors locally
- [ ] All tests pass locally
- [ ] CI workflows execute properly

2024-05-08 07:45 UTC, bratpiorka requested changes

2024-05-08 07:45 UTC, bratpiorka commented on test/CMakeLists.txt
> +    set_property(
I am not sure if this can ever be overridden by setting environment variables for scenarios where we would like to have different logging options

2024-05-08 08:19 UTC, PatKamin commented on test/CMakeLists.txt
> +        PROPERTY ENVIRONMENT "UMF_LOG=level:debug\;flush:debug\;output:stdout")
I think this could be merged leaving just `set_tests_properties` and providing two properties?

2024-05-08 13:57 UTC, lukaszstolarczuk commented on test/CMakeLists.txt
> +    set_property(
I'm afraid Rafał is right - we can't easily override the value...
I'm not sure how important of use case is that, though... but perhaps we should do this only on CI level.

When I finally add the script to run tests on CI we could set the logger there. For now, if needed we could set the logger in all workflows

2024-05-09 10:20 UTC, kswiecicki commented on test/CMakeLists.txt
> +        PROPERTY ENVIRONMENT "UMF_LOG=level:debug\;flush:debug\;output:stdout")
Done, I've merged it.

2024-05-09 10:21 UTC, kswiecicki commented on test/CMakeLists.txt
> +    set_property(
I'll refrain from adding similar change to `add_umf_benchmark` then.

2024-05-09 10:44 UTC, kswiecicki commented on test/CMakeLists.txt
> +    set_property(
Hm, due to the inflexibility of my change, I'll close this PR. Eventual logging changes will be done after @lukaszstolarczuk's CI script.

2024-05-09 10:44 UTC, closed without merging