Detect if umf has already been destroyed
oneapi-src/unified-memory-framework pull request #522
Opened 2024-05-27 13:14 UTC by ldorau

### Description

Add `umf_ba_is_destroyed()` and `umf_is_destroyed()`.

Do not run `umfPoolDestroy()` nor `umfMemoryProviderDestroy()` if umf has already been destroyed.

### Checklist
- [ ] Code compiles without errors locally
- [ ] All tests pass locally
- [ ] CI workflows execute properly

2024-05-27 13:43 UTC, vinser52 requested changes

2024-05-27 13:43 UTC, vinser52 commented on src/libumf_linux.c
> +int umf_is_destroyed(void) { return (TRACKER == NULL); }
I did not get the idea. If UMF is destroyed we cannot call any function from the library.

2024-05-27 14:26 UTC, ldorau commented on src/libumf_linux.c
> +int umf_is_destroyed(void) { return (TRACKER == NULL); }
It happens that OpenMP destroys UMF before `umfPoolDestroy()` and `umfMemoryProviderDestroy()` were called.

2024-05-27 21:29 UTC, vinser52 commented on src/libumf_linux.c
> +int umf_is_destroyed(void) { return (TRACKER == NULL); }
My question is the following: if UMF is destroyed, how adding `umf_is_destroyed` can help?

What "destroy" means in the OpenMP scenario? UMF library is unloaded? If so, no UMF functions can be called.

2024-05-28 06:38 UTC, ldorau commented on src/libumf_linux.c
> +int umf_is_destroyed(void) { return (TRACKER == NULL); }
"Destroy" in the OpenMP scenario means that the UMF's destructor has been called, but we do not if it was called or not and we want to call `umfPoolDestroy()` and `umfMemoryProviderDestroy()` in the destructor of OpenMP's allocator.

2024-05-28 06:40 UTC, ldorau commented on src/libumf_linux.c
> +int umf_is_destroyed(void) { return (TRACKER == NULL); }
Adding this patch helps - it prevents from a "use-after-free" segmentation fault.

2024-05-29 10:22 UTC, ldorau commented
> @ldorau @vinser52 would the approach proposed in #514 solve the issue ? This aims to solve a similar problem for llvm, but more generally.

No, because the UMF's constructor and destructor are called only once in this case before a segmentation fault:

1) UMF's constructor is called (I call dlopen(libumf.so))
2) UMF's destructor is called incorrectly by OpenMP on its own (I do not want that)
3) I call umfPoolDestroy() to free memory <<<--- it cause a "use-after-free" segmentation fault
4) UMF's destructor would be called correctly here

2024-05-29 10:25 UTC, ldorau commented on src/libumf_linux.c
> +int umf_is_destroyed(void) { return (TRACKER == NULL); }
> Ok, but why OpenMP allocator calls `umfPoolDestroy` after UMF's destructor is called. 

1) UMF's constructor is called (I call dlopen(libumf.so))
2) UMF's destructor is called incorrectly by OpenMP on its own (I do not know why and I do not want that)
3) I call umfPoolDestroy() to free memory <<<--- it cause a "use-after-free" segmentation fault
4) UMF's destructor (dlclose()) would be called correctly here

> Does it happen because UMF is used via `dlopen` by OpenMP 

Yes.

> and OpenMP calls `dlclose` in its destructor?

Probably, I am almost sure that's why.

2024-05-29 13:25 UTC, ldorau commented
So it is just a WA for an issue in OpenMP. I suppose it is jus a bug.

2024-05-29 14:22 UTC, igchor commented
> > @ldorau @vinser52 would the approach proposed in #514 solve the issue ? This aims to solve a similar problem for llvm, but more generally.
> 
> No, because the UMF's constructor and destructor are called only once in this case before a segmentation fault:
> 
> 1. UMF's constructor is called (I call dlopen(libumf.so))
> 2. UMF's destructor is called incorrectly by OpenMP on its own (I do not want that)
> 3. I call umfPoolDestroy() to free memory <<<--- it cause a "use-after-free" segmentation fault
> 4. UMF's destructor would be called correctly here

If the issue is because OpenMP calls dloclose in it's destructor as you wrote in a previous comment then the approach in #514 would actually help - that's the same problem as in llvm. My understanding is that when dlclose is called on UMF in other library destructor, the destructor of UMF can actually be called BEFORE that other one.

With the init/teardown API OpenMP would just call teardown once all other resources from UMF (pools, providers, ...) are freed and there would be no use-after-free.

2024-05-29 16:53 UTC, ldorau commented
> > > @ldorau @vinser52 would the approach proposed in #514 solve the issue ? This aims to solve a similar problem for llvm, but more generally.
> > 
> > No, because the UMF's constructor and destructor are called only once in this case before a segmentation fault:
> > 
> > 1. UMF's constructor is called (I call dlopen(libumf.so))
> > 2. UMF's destructor is called incorrectly by OpenMP on its own (I do not want that)
> > 3. I call umfPoolDestroy() to free memory <<<--- it cause a "use-after-free" segmentation fault
> > 4. UMF's destructor would be called correctly here
> 
> If the issue is because OpenMP calls dloclose in it's destructor as you wrote in a previous comment then the approach in #514 would actually help - that's the same problem as in llvm. My understanding is that when dlclose is called on UMF in other library destructor, the destructor of UMF can actually be called BEFORE that other one.
> 
> With the init/teardown API OpenMP would just call teardown once all other resources from UMF (pools, providers, ...) are freed and there would be no use-after-free.

Yes, this would help indeed.

2024-05-31 09:36 UTC, vinser52 commented
> > > > @ldorau @vinser52 would the approach proposed in #514 solve the issue ? This aims to solve a similar problem for llvm, but more generally.
> > > 
> > > 
> > > No, because the UMF's constructor and destructor are called only once in this case before a segmentation fault:
> > > 
> > > 1. UMF's constructor is called (I call dlopen(libumf.so))
> > > 2. UMF's destructor is called incorrectly by OpenMP on its own (I do not want that)
> > > 3. I call umfPoolDestroy() to free memory <<<--- it cause a "use-after-free" segmentation fault
> > > 4. UMF's destructor would be called correctly here
> > 
> > 
> > If the issue is because OpenMP calls dloclose in it's destructor as you wrote in a previous comment then the approach in #514 would actually help - that's the same problem as in llvm. My understanding is that when dlclose is called on UMF in other library destructor, the destructor of UMF can actually be called BEFORE that other one.
> > With the init/teardown API OpenMP would just call teardown once all other resources from UMF (pools, providers, ...) are freed and there would be no use-after-free.
> 
> Yes, this would help indeed.

Guys, I still do not quite understand how the proposed changes might fix the issue. If `dlclose` is called by OpenMP so why OpenMP calls UMF API after that? In that case, it should be fixed on the OpenMP side. If UMF is unloaded by the loader and OpenMP does not know about that, then I do not understand how the proposed functions might help. If UMF is unloaded already calling UMF function might cause crash because memory used by UMF library can be reused for something else.

2024-05-31 10:06 UTC, bratpiorka commented
> > Yes, this would help indeed.
> 
> Guys, I still do not quite understand how the proposed changes might fix the issue. If `dlclose` is called by OpenMP so why OpenMP calls UMF API after that? In that case, it should be fixed on the OpenMP side. If UMF is unloaded by the loader and OpenMP does not know about that, then I do not understand how the proposed functions might help. If UMF is unloaded already calling UMF function might cause crash because memory used by UMF library can be reused for something else.

I think if it was a bug in some important closed-source application, then we could consider such a WA, but if it comes from an Intel component that we have access to, then we should try to solve it by fixing the source of the problem first.

2024-06-03 13:28 UTC, ldorau commented
> Guys, I still do not quite understand how the proposed changes might fix the issue. If `dlclose` is called by OpenMP so why OpenMP calls UMF API after that? In that case, it should be fixed on the OpenMP side. If UMF is unloaded by the loader and OpenMP does not know about that, then I do not understand how the proposed functions might help. If UMF is unloaded already calling UMF function might cause crash because memory used by UMF library can be reused for something else.

@vinser52 @bratpiorka @igchor I have debugged it more and it turned out that only in one group ("Offload") of tests the UMF's destructor is called **by the OS program loader** before the destructor of the OpenMP library which uses UMF. 
So I think that the solution proposed by @igchor would solve this issue. I have no idea now how we could fix it in another way.

2024-06-05 08:45 UTC, ldorau commented
Replaced with https://github.com/oneapi-src/unified-memory-framework/pull/530

2024-06-05 08:45 UTC, closed without merging