cleanup include ze_api.h
oneapi-src/unified-memory-framework pull request #525
Opened 2024-05-28 07:09 UTC by bratpiorka

### Description

ze_api.h should be always:
* included from the deps (build/_deps/level-zero-loader-***) for all internal code including tests
* included from the system paths in the examples

### Checklist
- [ ] Code compiles without errors locally
- [ ] All tests pass locally
- [ ] CI workflows execute properly

2024-05-29 09:01 UTC, kswiecicki approved these changes

2024-05-29 09:29 UTC, KFilipek requested changes
If you plan to reorder headers, please, use Coding style guidelines. 
As I remember, external headers should be in a separate block. Currently, they are mixed.

2024-05-29 13:09 UTC, ldorau approved these changes

2024-05-31 10:02 UTC, bratpiorka commented
> If you plan to reorder headers, please, use Coding style guidelines. As I remember, external headers should be in a separate block. Currently, they are mixed. E.g. ze_api.h or mutex

We don't have strict coding style rules - we only have what's here: https://github.com/oneapi-src/unified-memory-framework/blob/main/CONTRIBUTING.md#code-style
But regarding the order - I keep the "standard" includes fist (<mutex>), then UMF interface that is supposed to be installed (<umf/*>) and local includes at the end. In "test/providers/provider_level_zero.cpp" I threat "ze_api.h" as a local header, because it is downloaded by UMF to the _deps folder and I intentionally keep it with the other local files

2024-05-31 10:03 UTC, kswiecicki commented
> If you plan to reorder headers, please, use Coding style guidelines. As I remember, external headers should be in a separate block. Currently, they are mixed. E.g. ze_api.h or mutex

From what I see, the `ze_api.h` header is treated as external in examples, and as internal in umf sources/tests. In case of examples, @bratpiorka mentioned it should come from system paths from the user.

2024-06-03 08:54 UTC, KFilipek approved these changes

2024-06-03 08:55 UTC, merged