Add a RUNPATH to installed libraries
oneapi-src/unified-memory-framework pull request #892
Opened 2024-11-13 08:27 UTC by PatKamin

### Description

This is a cherry-picked patch merged to the v0.9 branch: #882 

### Checklist

- [x] Code compiles without errors locally
- [ ] All tests pass locally
- [ ] CI workflows execute properly

- [ ] CI workflows, not executed per PR (e.g. Nightly), execute properly 
- [ ] New tests added, especially if they will fail without my changes
- [ ] Added/extended example(s) to cover this functionality
- [ ] Extended the README/documentation
- [ ] All newly added source files have a license
- [ ] All newly added source files are referenced in CMake files
- [ ] Logger (with debug/info/... messages) is used

2024-11-13 08:29 UTC, bratpiorka approved these changes

2024-11-13 15:14 UTC, lukaszstolarczuk requested changes

2024-11-13 15:14 UTC, lukaszstolarczuk commented on src/CMakeLists.txt
> +    set(CMAKE_INSTALL_RPATH "\$ORIGIN")
just want to make sure - isn't there a better solution to that problem...? 😉 now, some random value of `$ORIGIN` could make unexpected issues, or something...?

2024-11-14 10:19 UTC, lukaszstolarczuk commented on src/CMakeLists.txt
> +    set(CMAKE_INSTALL_RPATH "\$ORIGIN")
we can do similarly like we have for hwloc name change and only set it when required

2024-11-20 09:24 UTC, PatKamin commented on src/CMakeLists.txt
> +        set(CMAKE_INSTALL_RPATH ${UMF_INSTALL_RPATH})
Added

2024-11-20 09:24 UTC, PatKamin commented on CMakeLists.txt
> +set(UMF_INSTALL_RPATH
Moved

2024-11-20 09:24 UTC, PatKamin commented on src/CMakeLists.txt
> +    if(NOT "${UMF_INSTALL_RPATH}" STREQUAL "")
Yes, it suffices, thanks.

2024-11-20 09:25 UTC, PatKamin commented on CMakeLists.txt
> +        "Set the runtime search path to the directory containing hwloc library")
Now it's clearer, thanks.

2024-11-20 09:28 UTC, lukaszstolarczuk approved these changes

2024-11-20 12:07 UTC, PatKamin commented on CMakeLists.txt
> +    set(UMF_INSTALL_RPATH
Fixed

2024-11-20 14:20 UTC, bratpiorka approved these changes

2024-11-20 14:21 UTC, merged