Implement IPC API of the Coarse provider
oneapi-src/unified-memory-framework pull request #907
Opened 2024-11-18 12:19 UTC by ldorau

### Description

Implement IPC API of the Coarse provider.

Split and merge in Coarse provider to enable IPC API.
Coarse provider has to always call:
- `umfMemoryProviderAllocationSplit(upstream_provider)` or
- `umfMemoryProviderAllocationMerge(upstream_provider)`
when splitting or merging memory blocks,
because the IPC API would not work on split/merged memory
blocks otherwise.

Fixes: #900

### Checklist

- [ ] Code compiles without errors locally
- [ ] All tests pass locally
- [ ] CI workflows execute properly

2024-11-18 17:44 UTC, bratpiorka commented
please add the following test:
* use Proxy Pool, Coarse Provider and L0 Provider
* alloc 4KB, free it - this way L0 should allocate single 4KB buffer that should be kept inside the Coarse Provider
* alloc 2KB twice - Coarse Prov should call split
* open IPC handle on both allocations

2024-11-18 21:57 UTC, lplewa requested changes
This PR will not work with L0/Cuda providers as they do not (and probably will not) have split/merge functionality. 

Not sure how we should solve this issue. Tracking provider all ready has this functionality on the pool level . We could copy it to coarse provider - but is this HORRIBLE idea (code duplication and performance implications).

Performance is something which should also consider. We have too much trackers, list, and trees. I'm currently working on benchmark those, but still in my opinion, we should try to limit those to absolute minimum. When at each level we have minimum one extra data structure with non constant time complexity of inserts or delete. 

For now i would recommend to make this PR a draft, and have good architectural discussion about this issue.

2024-11-18 23:06 UTC, vinser52 commented
> This PR will not work with L0/Cuda providers as they do not (and probably will not) have split/merge functionality.
> 
> Not sure how we should solve this issue. Tracking provider all ready has this functionality on the pool level . We could copy it to coarse provider - but is this HORRIBLE idea (code duplication and performance implications).
> 
> Performance is something which should also consider. We have too much trackers, list, and trees. I'm currently working on benchmark those, but still in my opinion, we should try to limit those to absolute minimum. When at each level we have minimum one extra data structure with non constant time complexity of inserts or delete.
> 
> For now i would recommend to make this PR a draft, and have good architectural discussion about this issue.

I totally agree with @lplewa. In fact, the coarse provider implements memory pooling logic, but it is implemented as a provider and used inside UMF stack as a provider. As a result, it resides below our memory tracker, because tracking provider is always on the top (between the pool manager and memory providers). I agree that we need an architecture discussion current implementation experience shows that current approach has issues.

2024-11-19 10:11 UTC, ldorau commented
> please add the following test:
> 
> * use Proxy Pool, Coarse Provider and L0 Provider
> * alloc 4KB, free it - this way L0 should allocate single 4KB buffer that should be kept inside the Coarse Provider
> * alloc 2KB twice - Coarse Prov should call split
> * open IPC handle on both allocations

```c
static umf_result_t ze_memory_provider_allocation_split(void *provider,
                                                        void *ptr,
                                                        size_t totalSize,
                                                        size_t firstSize) {
    (void)provider;
    (void)ptr;
    (void)totalSize;
    (void)firstSize;

    // TODO not supported yet
    return UMF_RESULT_ERROR_NOT_SUPPORTED;
}
```

2024-11-26 07:07 UTC, ldorau commented
Replaced by #931

2024-11-26 07:07 UTC, closed without merging