Implement size limit for the cache of opened IPC handles
oneapi-src/unified-memory-framework pull request #998
Opened 2024-12-17 10:19 UTC by vinser52

### Description
It is a follow-up of the #736. Add an environment variable that allows setting a limit for the size of the cache of opened IPC handles.

### Checklist

- [ ] Code compiles without errors locally
- [ ] All tests pass locally
- [ ] CI workflows execute properly
- [ ] New tests added, especially if they will fail without my changes
- [ ] Extended the README/documentation

2024-12-17 10:20 UTC, vinser52 commented
TODO: need to add tests

2024-12-17 11:39 UTC, vinser52 commented
> and probably you could add some info about this var into README, pls

Sure, I will do that.

2025-02-13 09:01 UTC, bratpiorka commented
@vinser52 what are the plans for this PR? Is it working and ready to review?

2025-02-17 13:16 UTC, vinser52 commented
> @vinser52 what are the plans for this PR? Is it working and ready to review?

It is not ready yet. I am working on it right now. Need to implement proper refcounting and eviction.

2025-02-21 13:17 UTC, vinser52 commented on test/ipcFixtures.hpp
> -TEST_P(umfIpcTest, GetPoolByOpenedHandle) {
@bratpiorka compatibility tests failed because memory regions retrieved from the `umfOpenIPCHandle` function do not belong to the pool anymore (as we agreed earlier). That is why I removed this `TEST_P(umfIpcTest, GetPoolByOpenedHandle)` test.

Could you please suggest how to fix the compatibility tests?

2025-02-21 16:08 UTC, vinser52 commented
> and probably you could add some info about this var into README, pls

@lukaszstolarczuk Done. I updated the online documentation.

2025-02-21 17:15 UTC, bratpiorka commented on test/ipcFixtures.hpp
> -TEST_P(umfIpcTest, GetPoolByOpenedHandle) {
Please add a filter to the tests in the compatibility workflow with an appropriate comment.

2025-02-21 22:55 UTC, vinser52 commented on test/ipcFixtures.hpp
> -TEST_P(umfIpcTest, GetPoolByOpenedHandle) {
Done

2025-02-24 07:19 UTC, ldorau commented on .github/workflows/reusable_compatibility.yml
> +        GTEST_FILTER="-*umfIpcTest.GetPoolByOpenedHandle*"
Could you explain why this test is not compatible?

2025-02-24 07:20 UTC, ldorau commented on docs/config/api.rst
> +UMF employs IPC caching to avoid multiple IPC handles being created for the same
👍 very useful

2025-02-24 07:54 UTC, ldorau commented on .github/workflows/reusable_compatibility.yml
> +        GTEST_FILTER="-*umfIpcTest.GetPoolByOpenedHandle*"
I have already found the answer:
https://github.com/oneapi-src/unified-memory-framework/pull/998/files#r1965460346
:-)

2025-02-24 08:51 UTC, ldorau requested changes

2025-02-24 08:51 UTC, ldorau commented on src/provider/provider_tracking.c
> +            p->hTracker, value->mapped_base_ptr);
Please update the comment above.

2025-02-24 08:51 UTC, ldorau commented on src/provider/provider_tracking.c
>              // cannot change behaviour of the upstream provider.
Please update this comment and the error message below

2025-02-24 09:31 UTC, vinser52 commented on src/ipc_cache.c
> +            } while (candidate != cache->global->lru_list->prev);
You are correct. We cannot evict items that are used (`refcount > 0`). So our cache size limit is a soft limit.

2025-02-24 09:42 UTC, vinser52 commented on test/ipcFixtures.hpp
> -TEST_P(umfIpcTest, GetPoolByOpenedHandle) {
I have to filter out the test in the compatibility flow (an older version of the tests, where this test is present, is used). However, in the current version, this test is just removed.

I did not get your point regarding the comment, where do you suggest adding the comment?

2025-02-24 09:42 UTC, vinser52 commented on src/provider/provider_tracking.c
>              // cannot change behaviour of the upstream provider.
I have updated the error message, but I did not get how you suggested changing the comment.

2025-02-24 10:07 UTC, ldorau commented on src/ipc_cache.c
> +            } while (candidate != cache->global->lru_list->prev);
OK

2025-02-24 10:12 UTC, ldorau commented on test/ipcFixtures.hpp
> -TEST_P(umfIpcTest, GetPoolByOpenedHandle) {
I see, so it is OK now. If there is no skipped test now, there is no need to add a comment.

2025-02-24 10:18 UTC, ldorau requested changes
What about this error?
```
[ RUN      ] umfIpcTestSuite/umfIpcTest.ConcurrentOpenCloseHandles/0
==================
WARNING: ThreadSanitizer: data race (pid=13011)
  Write of size 8 at 0x7f846e283628 by thread T102 (mutexes: write M0, write M1):
    #0 critnib_insert /home/runner/work/unified-memory-framework/unified-memory-framework/src/critnib/critnib.c:402:21 (umf_test-ipc_max_opened_limit+0x14a655) (BuildId: 226b1072e2389a0c07c55ebae2dca25888ff8cdb)
    #1 umfMemoryTrackerAddIpcSegment /home/runner/work/unified-memory-framework/unified-memory-framework/src/provider/provider_tracking.c:135:9 (umf_test-ipc_max_opened_limit+0x1499c7) (BuildId: 226b1072e2389a0c07c55ebae2dca25888ff8cdb)
    #2 upstreamOpenIPCHandle /home/runner/work/unified-memory-framework/unified-memory-framework/src/provider/provider_tracking.c:770:11 (umf_test-ipc_max_opened_limit+0x14967b) (BuildId: 226b1072e2389a0c07c55ebae2dca25888ff8cdb)
    #3 trackingOpenIpcHandle /home/runner/work/unified-memory-framework/unified-memory-framework/src/provider/provider_tracking.c:825:19 (umf_test-ipc_max_opened_limit+0x1485d1) (BuildId: 226b1072e2389a0c07c55ebae2dca25888ff8cdb)
    #4 umfMemoryProviderOpenIPCHandle /home/runner/work/unified-memory-framework/unified-memory-framework/src/memory_provider.c:362:12 (umf_test-ipc_max_opened_limit+0x145e7a) (BuildId: 226b1072e2389a0c07c55ebae2dca25888ff8cdb)
    #5 umfOpenIPCHandle /home/runner/work/unified-memory-framework/unified-memory-framework/src/ipc.c:137:24 (umf_test-ipc_max_opened_limit+0x143452) (BuildId: 226b1072e2389a0c07c55ebae2dca25888ff8cdb)
    #6 umfIpcTest::concurrentOpenCloseHandles(bool)::'lambda'(unsigned long)::operator()(unsigned long) const /home/runner/work/unified-memory-framework/unified-memory-framework/test/ipcFixtures.hpp:404:21 (umf_test-ipc_max_opened_limit+0x[119](https://github.com/oneapi-src/unified-memory-framework/actions/runs/13476730706/job/37657032790#step:7:120)046) (BuildId: 226b1072e2389a0c07c55ebae2dca25888ff8cdb)
    #7 void umf_test::parallel_exec<umfIpcTest::concurrentOpenCloseHandles(bool)::'lambda'(unsigned long)&>(unsigned long, umfIpcTest::concurrentOpenCloseHandles(bool)::'lambda'(unsigned long)&)::'lambda'(unsigned long)::operator()(unsigned long) const /home/runner/work/unified-memory-framework/unified-memory-framework/test/common/multithread_helpers.hpp:27:47 (umf_test-ipc_max_opened_limit+0x118dd5) (BuildId: 226b1072e2389a0c07c55ebae2dca25888ff8cdb)
```
https://github.com/oneapi-src/unified-memory-framework/actions/runs/13476730706/job/37657032790

2025-02-24 11:19 UTC, vinser52 commented
> What about this error?
> 
> ```
> [ RUN      ] umfIpcTestSuite/umfIpcTest.ConcurrentOpenCloseHandles/0
> ==================
> WARNING: ThreadSanitizer: data race (pid=13011)
>   Write of size 8 at 0x7f846e283628 by thread T102 (mutexes: write M0, write M1):
>     #0 critnib_insert /home/runner/work/unified-memory-framework/unified-memory-framework/src/critnib/critnib.c:402:21 (umf_test-ipc_max_opened_limit+0x14a655) (BuildId: 226b1072e2389a0c07c55ebae2dca25888ff8cdb)
>     #1 umfMemoryTrackerAddIpcSegment /home/runner/work/unified-memory-framework/unified-memory-framework/src/provider/provider_tracking.c:135:9 (umf_test-ipc_max_opened_limit+0x1499c7) (BuildId: 226b1072e2389a0c07c55ebae2dca25888ff8cdb)
>     #2 upstreamOpenIPCHandle /home/runner/work/unified-memory-framework/unified-memory-framework/src/provider/provider_tracking.c:770:11 (umf_test-ipc_max_opened_limit+0x14967b) (BuildId: 226b1072e2389a0c07c55ebae2dca25888ff8cdb)
>     #3 trackingOpenIpcHandle /home/runner/work/unified-memory-framework/unified-memory-framework/src/provider/provider_tracking.c:825:19 (umf_test-ipc_max_opened_limit+0x1485d1) (BuildId: 226b1072e2389a0c07c55ebae2dca25888ff8cdb)
>     #4 umfMemoryProviderOpenIPCHandle /home/runner/work/unified-memory-framework/unified-memory-framework/src/memory_provider.c:362:12 (umf_test-ipc_max_opened_limit+0x145e7a) (BuildId: 226b1072e2389a0c07c55ebae2dca25888ff8cdb)
>     #5 umfOpenIPCHandle /home/runner/work/unified-memory-framework/unified-memory-framework/src/ipc.c:137:24 (umf_test-ipc_max_opened_limit+0x143452) (BuildId: 226b1072e2389a0c07c55ebae2dca25888ff8cdb)
>     #6 umfIpcTest::concurrentOpenCloseHandles(bool)::'lambda'(unsigned long)::operator()(unsigned long) const /home/runner/work/unified-memory-framework/unified-memory-framework/test/ipcFixtures.hpp:404:21 (umf_test-ipc_max_opened_limit+0x[119](https://github.com/oneapi-src/unified-memory-framework/actions/runs/13476730706/job/37657032790#step:7:120)046) (BuildId: 226b1072e2389a0c07c55ebae2dca25888ff8cdb)
>     #7 void umf_test::parallel_exec<umfIpcTest::concurrentOpenCloseHandles(bool)::'lambda'(unsigned long)&>(unsigned long, umfIpcTest::concurrentOpenCloseHandles(bool)::'lambda'(unsigned long)&)::'lambda'(unsigned long)::operator()(unsigned long) const /home/runner/work/unified-memory-framework/unified-memory-framework/test/common/multithread_helpers.hpp:27:47 (umf_test-ipc_max_opened_limit+0x118dd5) (BuildId: 226b1072e2389a0c07c55ebae2dca25888ff8cdb)
> ```
> 
> https://github.com/oneapi-src/unified-memory-framework/actions/runs/13476730706/job/37657032790

Yeah, I saw it. Looks really strange because the data race is reported for the node that is not linked to the tree yet (so other threads cannot access it). And it is linked to the tree at line 409 using `utils_atomic_store_release`.

2025-02-24 13:24 UTC, ldorau commented
> > https://github.com/oneapi-src/unified-memory-framework/actions/runs/13476730706/job/37657032790
> 
> Yeah, I saw it. Looks really strange because the data race is reported for the node that is not linked to the tree yet (so other threads cannot access it). And it is linked to the tree at line 409 using `utils_atomic_store_release`.

Yes, exactly. It looks really strange - like false-positive. More over, there is `VALGRIND_HG_DRD_DISABLE_CHECKING(m, sizeof(struct critnib_node));` just before.

2025-02-24 13:33 UTC, ldorau commented
> > > https://github.com/oneapi-src/unified-memory-framework/actions/runs/13476730706/job/37657032790
> > 
> > 
> > Yeah, I saw it. Looks really strange because the data race is reported for the node that is not linked to the tree yet (so other threads cannot access it). And it is linked to the tree at line 409 using `utils_atomic_store_release`.
> 
> Yes, exactly. It looks really strange - like false-positive. More over, there is `VALGRIND_HG_DRD_DISABLE_CHECKING(m, sizeof(struct critnib_node));` just before.

Ah, this node has been already linked, because this is a deleted node that has been reused here:
```c
static struct critnib_node *alloc_node(struct critnib *__restrict c) {
    if (!c->deleted_node) {
        return umf_ba_global_alloc(sizeof(struct critnib_node));
    }

    struct critnib_node *n = c->deleted_node;

    c->deleted_node = n->child[0];
    VALGRIND_ANNOTATE_NEW_MEMORY(n, sizeof(*n));

    return n;
}
```
(lines 273-284)

2025-02-24 13:46 UTC, ldorau commented
I have encountered also another issue:
https://github.com/ldorau/unified-memory-framework/actions/runs/13499357001/job/37713739063
```
[ RUN      ] FileProviderDifferentPoolsTest/umfIpcTest.ConcurrentDestroyIpcHandlers/1
=================================================================
==13018==ERROR: AddressSanitizer: use-after-poison on address 0x7f3f50300000 at pc 0x7f3f56639c23 bp 0x7ffffdbc20a0 sp 0x7ffffdbc1848
WRITE of size 127728 at 0x7f3f50300000 thread T0
    #0 0x7f3f56639c22 in __interceptor_memset ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:799
    #1 0x7f3f56052489 in rml::pool_create_v1(long, rml::MemPoolPolicy const*, rml::MemoryPool**) (/lib/x86_64-linux-gnu/libtbbmalloc.so.2+0x13489)
    #2 0x55a18103342e in tbb_pool_initialize /home/runner/work/unified-memory-framework/unified-memory-framework/src/pool/pool_scalable.c:295
    #3 0x55a181016a90 in umfPoolCreateInternal /home/runner/work/unified-memory-framework/unified-memory-framework/src/memory_pool.c:67
    #4 0x55a1810173a4 in umfPoolCreate /home/runner/work/unified-memory-framework/unified-memory-framework/src/memory_pool.c:146
    #5 0x55a180f6eba9 in umfIpcTest::makePool() (/home/runner/work/unified-memory-framework/unified-memory-framework/build/test/umf_test-provider_file_memory_ipc+0x3fdba9)
    #6 0x55a180f56e9e in umfIpcTest_ConcurrentDestroyIpcHandlers_Test::TestBody() /home/runner/work/unified-memory-framework/unified-memory-framework/test/ipcFixtures.hpp:723
    #7 0x55a18119a0d5 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/runner/work/unified-memory-framework/unified-memory-framework/build/_deps/googletest-src/googletest/src/gtest.cc:2638
    #8 0x55a181174c8f in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/runner/work/unified-memory-framework/unified-memory-framework/build/_deps/googletest-src/googletest/src/gtest.cc:2674
    #9 0x55a1810beb07 in testing::Test::Run() /home/runner/work/unified-memory-framework/unified-memory-framework/build/_deps/googletest-src/googletest/src/gtest.cc:2713
```

2025-02-24 13:51 UTC, ldorau commented
And again a very similar one: https://github.com/ldorau/unified-memory-framework/actions/runs/13499491223/job/37714164104

2025-03-06 09:59 UTC, ldorau requested changes

2025-03-06 09:59 UTC, ldorau commented on src/provider/provider_tracking.c
> +                                        p->pool->provider, cache_entry);
Does `p->pool->provider` break encapsulation?
Should we expose UMF internals to the provider's implementation?

2025-03-06 10:11 UTC, ldorau reviewed
LGTM

2025-03-06 10:11 UTC, ldorau approved these changes
LGTM except the above question

2025-03-06 11:16 UTC, vinser52 commented on src/provider/provider_tracking.c
> +                                        p->pool->provider, cache_entry);
I consider the tracking provider as an internal part because it is not a public provider it is just a memory-tracking utility implemented as a provider for our convenience.

But it is a good catch. Today we always create a `pool` and get an IPC handler from the pool. And tracking provider is always created together with a pool.  And the IPC handler is a tracking memory provider in fact.
However, we are considering adding an API that allows IPC handler creation from scratch (without creating a memory pool). In that case, we will create a tracker provider without a pool. So `p->pool` might be `NULL` in the future...

Let me think more about that.

2025-03-07 13:50 UTC, bratpiorka commented on test/CMakeLists.txt
> +    LIBS ${UMF_UTILS_FOR_TEST} ENVS "UMF_MAX_OPENED_IPC_HANDLES=10")
nit: please extend also 'add_umf_test' in /.cmake-format

2025-03-07 13:51 UTC, bratpiorka commented on src/provider/provider_tracking.c
> +    ;
;

2025-03-07 15:45 UTC, vinser52 commented on src/provider/provider_tracking.c
> +    ;
Done

2025-03-07 15:45 UTC, vinser52 commented on test/CMakeLists.txt
> +    LIBS ${UMF_UTILS_FOR_TEST} ENVS "UMF_MAX_OPENED_IPC_HANDLES=10")
Done

2025-03-07 15:45 UTC, vinser52 commented on .github/workflows/reusable_compatibility.yml
> +        GTEST_FILTER="-*umfIpcTest.GetPoolByOpenedHandle*"
Done

2025-03-10 11:21 UTC, vinser52 commented on src/provider/provider_tracking.c
> +                                        p->pool->provider, cache_entry);
I added a TODO comment. it is just an implementation detail that can be changed in the future.

2025-03-10 12:55 UTC, KFilipek commented on test/CMakeLists.txt
> +        set_tests_properties(${TEST_NAME} PROPERTIES ENVIRONMENT ${ARG_ENVS})
I'm not a fan of adding such env functionality only for one tests.
Please add `set_tests_properties` just after `add_umf_test` and it should work.
Currently, I try to rewrite from scratch all CMake files to remove such boilerplate.

2025-03-10 12:59 UTC, vinser52 commented on test/CMakeLists.txt
> +        set_tests_properties(${TEST_NAME} PROPERTIES ENVIRONMENT ${ARG_ENVS})
The problem is that the test should be disabled in the previous version of UMF.
In the current version (main branch) the test is removed, but the compatibility test failed without this environment because we need somehow to disable it in the previous versions.

2025-03-10 13:56 UTC, igchor approved these changes

2025-03-10 16:14 UTC, KFilipek commented on test/CMakeLists.txt
> +        set_tests_properties(${TEST_NAME} PROPERTIES ENVIRONMENT ${ARG_ENVS})
So, as I understand it should be enough:
```cmake
if(TARGET ipc_max_opened_limit)
  set_tests_properties(ipc_max_opened_limit PROPERTIES ENVIRONMENT "UMF_MAX_OPENED_IPC_HANDLES=10")
endif()
```
When target is not created then is no need to set it up, it should do the same as your code.

2025-03-11 10:43 UTC, vinser52 commented on test/CMakeLists.txt
> +        set_tests_properties(${TEST_NAME} PROPERTIES ENVIRONMENT ${ARG_ENVS})
Sorry, please disregard my previous comment: I misunderstood your initial feedback.

> So, as I understand it should be enough:
> 
> ```cmake
> if(TARGET ipc_max_opened_limit)
>   set_tests_properties(ipc_max_opened_limit PROPERTIES ENVIRONMENT "UMF_MAX_OPENED_IPC_HANDLES=10")
> endif()
> ```
> When target is not created then is no need to set it up, it should do the same as your code.

Today `add_umf_test` function is generic and allows the setup any environment for any test. Why should we make it test specific like you proposed? What if tomorrow I want to create another test with another environment variable? And actually we will do that in the future for more extensive IPC testing.

2025-03-11 10:44 UTC, ldorau commented
@vinser52 please rebase

2025-03-11 11:45 UTC, vinser52 commented
> @vinser52 please rebase

Done

2025-03-11 12:26 UTC, KFilipek approved these changes

2025-03-11 12:27 UTC, merged